// The service worker, as a source string the build stamps and emits.
//
// Wallgraph is one file. That makes offline a genuinely reachable promise rather
// than an engineering project: cache index.html and the editor works on a train.
// The worker only ships with a hosted build — a `dist/index.html` opened from
// disk needs no worker and could not register one anyway.
//
// **Network-first, always.** netlify.toml sets `Cache-Control: no-cache` on the
// HTML with a comment saying never to let a proxy pin an old copy, and a service
// worker is a proxy that lives in the user's browser and outlives the tab. A
// cache-first worker would be exactly the stale editor that header exists to
// prevent, and it would be far harder to dislodge. So the cache is a fallback
// for when the network fails, and nothing else.
//
// The cache name carries the build's version and a hash of the page, so a deploy
// leaves the previous cache orphaned and `activate` deletes it. There is no
// migration path and none is wanted: the cache holds nothing that is not
// re-fetchable.

/** Files worth having before the network is gone. Everything else is cached as
 *  it is visited, which is the honest scope for pages a visitor may never open. */
const PRECACHE = ["/", "/manifest.webmanifest"];

export function serviceWorker(version: string, hash: string): string {
  return `// Generated by scripts/site/sw.ts — do not edit.
const CACHE = "wallgraph-${version}-${hash}";
const PRECACHE = ${JSON.stringify(PRECACHE)};

self.addEventListener("install", event => {
  // skipWaiting so a deploy takes effect on the next load rather than after
  // every tab is closed. Safe here: the editor holds its document in memory and
  // in storage, not in the worker, so a swapped worker loses nothing.
  self.skipWaiting();
  event.waitUntil(caches.open(CACHE).then(c => c.addAll(PRECACHE)).catch(() => {}));
});

self.addEventListener("activate", event => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) if (key !== CACHE) await caches.delete(key);
    await self.clients.claim();
  })());
});

self.addEventListener("fetch", event => {
  const req = event.request;
  // Only our own GETs. A POST or a cross-origin request is none of our business,
  // and caching one would be a surprise rather than a feature.
  if (req.method !== "GET" || new URL(req.url).origin !== self.location.origin) return;

  event.respondWith((async () => {
    try {
      const fresh = await fetch(req);
      // Opaque and error responses are not worth keeping; a cached 404 is worse
      // than no cache at all.
      if (fresh.ok && fresh.type === "basic") {
        const cache = await caches.open(CACHE);
        cache.put(req, fresh.clone()).catch(() => {});
      }
      return fresh;
    } catch (err) {
      const hit = await caches.match(req);
      if (hit) return hit;
      // A navigation to a page never visited, with no network: the editor is
      // the one thing always precached, so it is a better answer than a failure.
      if (req.mode === "navigate") {
        const shell = await caches.match("/");
        if (shell) return shell;
      }
      throw err;
    }
  })());
});
`;
}

/**
 * The inline registration, for the hosted page only.
 *
 * Guarded three ways because this exact script also ends up in a file people
 * open from a memory stick: no serviceWorker on the navigator (older browsers,
 * some embedded views), a non-http origin (file://), and a registration that
 * rejects for any reason at all. A failed registration must cost the visitor
 * nothing — the editor works fine without one.
 */
export const registration = `if("serviceWorker"in navigator&&location.protocol.startsWith("http")){` +
  `addEventListener("load",function(){navigator.serviceWorker.register("/sw.js").catch(function(){})})}`;
