// Generated service worker. Hosted builds use network-first requests with an
// offline cache. Cache names include the build version and page hash; activation
// removes obsolete caches.

/** Files cached during installation; other same-origin files are cached after use. */
const PRECACHE = ["/", "/manifest.webmanifest"];

export function serviceWorker(version: string, hash: string): string {
  return `// Generated by scripts/site/sw.ts — do not edit.
const CACHE = "wallgraph-${version}-${hash}";
const PRECACHE = ${JSON.stringify(PRECACHE)};

self.addEventListener("install", event => {
  // Documents are not stored in the worker, so immediate activation is safe.
  self.skipWaiting();
  event.waitUntil(caches.open(CACHE).then(c => c.addAll(PRECACHE)).catch(() => {}));
});

self.addEventListener("activate", event => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) if (key !== CACHE) await caches.delete(key);
    await self.clients.claim();
  })());
});

self.addEventListener("fetch", event => {
  const req = event.request;
  // Cache only same-origin GET requests.
  if (req.method !== "GET" || new URL(req.url).origin !== self.location.origin) return;

  event.respondWith((async () => {
    try {
      const fresh = await fetch(req);
      // Cache only successful, non-opaque responses.
      if (fresh.ok && fresh.type === "basic") {
        const cache = await caches.open(CACHE);
        cache.put(req, fresh.clone()).catch(() => {});
      }
      return fresh;
    } catch (err) {
      const hit = await caches.match(req);
      if (hit) return hit;
      // Fall back to the precached editor for uncached offline navigations.
      if (req.mode === "navigate") {
        const shell = await caches.match("/");
        if (shell) return shell;
      }
      throw err;
    }
  })());
});
`;
}

/** Hosted-page registration with capability, protocol and rejection guards. */
export const registration = `if("serviceWorker"in navigator&&location.protocol.startsWith("http")){` +
  `addEventListener("load",function(){navigator.serviceWorker.register("/sw.js").catch(function(){})})}`;
